spring:
  application:
    name: "mica-lite-example"
  profiles:
    active: "dev"
management:
  endpoints:
    web:
      exposure:
        include: '*'
mica:
  xss:
    mode: validate
# springdoc 支持 knife4j
springdoc:
  swagger-ui:
    urls:
      - name: swagger
        url: /v3/api-docs
